// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqK1EXzCgvy0PkmfbHc-kjR3ZBvy5npBM',
    appId: '1:560905306057:web:7d64e80f582baa09a4b218',
    messagingSenderId: '560905306057',
    projectId: 'sistemalogin-60d14',
    authDomain: 'sistemalogin-60d14.firebaseapp.com',
    storageBucket: 'sistemalogin-60d14.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuDFkk4vZ-Mai8YyqlnABKrDbbf01lWkA',
    appId: '1:560905306057:android:b1f750f41cff1bf6a4b218',
    messagingSenderId: '560905306057',
    projectId: 'sistemalogin-60d14',
    storageBucket: 'sistemalogin-60d14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOQ4U0I4g1BiO4MnzTVGV5USEug4mtgms',
    appId: '1:560905306057:ios:e3c8f6d5f7737298a4b218',
    messagingSenderId: '560905306057',
    projectId: 'sistemalogin-60d14',
    storageBucket: 'sistemalogin-60d14.appspot.com',
    iosClientId: '560905306057-r6dsu1rlc6khej570t0b3nbdaknd9nt6.apps.googleusercontent.com',
    iosBundleId: 'com.example.sistemLogin',
  );
}
